name: Deploy a Azure

on:
  push:
    branches:
      - main  # Revisa si tu rama se llama 'main' o 'master'# comentando solo para aplicar cambios

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          
      - script: |
         npm install --legacy-peer-deps
         npm run build
       displayName: 'npm install and build'

      - name: Desplegar a Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'voto-libre'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
